### ISSUE TITLE
Does every app need to be it's own repo?

### ISSUE THREAD

**Issue by rosskarchner** [cfpb/back-end#8]
3 years or so ago, I cam back from DjangoCon, full or religion. The religion of breaking our Django projects out into per-app repositories.  

Lately, I've been thinking that this has created more problems than it solves. It's complicates everything from developer workstation setup to deployment. It doesn't even seem like a common way to work with Django. It's been a trail of tears.

The direction I've been thinking about advocating for V1 is:
- New apps are always incubated in the project.
- consider "graduating" an app if:
  - we could use it in multiple projects (say, cf.gov and intranet)
  - This is a little squishy, but if an app (or set of apps) is big enough, and largely independent of a particular site (like eregs)
  - Or if there is external demand for it-- someone outside the bureau tells us they want use a particular app (or want to contribute to a particular app)

**Comment by rosskarchner** [comment]
I believe @higs4281 has an opinion on this.

**Comment by higs4281** [comment]
This might discourage experimentation, or could be seen as limiting, but it would make it much easier for new developers to jump in the Django pool and quickly contribute.  

If an app doesn't need to "graduate," it saves a pile of grief and wasted cycles spent trying to make it work as both a stand-alone project and a team player. Developing in branches or forks -- instead of scattered repos that all use different settings schemes and delivery paths -- makes sense to me.

It does raise the mothership question -- if any part of the site can't be public, does that lock the whole enterprise into GHE?

**Comment by rosskarchner** [comment]
I think we're headed in the other direction: apps will live in the public cfgov repo. If something needs to be private, then that could be another reason an app could be maintained as a standalone.
